spring:
  datasource:
    username: postgres
    password: bHa8Hn9OBm
    url: jdbc:postgresql://y-postgres-postgresql.development.svc.cluster.local:5432/account
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    addresses: rabbit-rabbitmq.development.svc.cluster.local:5672
server:
 port: 8095
